function [O1, O2] = LogisticX(P, I1, I2, s)
% LogisticX - High-performance Logistic Crossover for Real-Coded GA
%
% This implementation follows the standard LogX logic:
% Offspring are generated by perturbing parents using a Logistic distribution.
% The heavy-tailed nature of the Logistic distribution enhances exploration
% compared to Gaussian-based operators like UNDX.
%
% Inputs:
%   P  : (D x N) Matrix, Current Population
%   I1 : (1 x n) Vector, Indices of first parents
%   I2 : (1 x n) Vector, Indices of second parents
%   s  : Scale parameter (default = 1.0). 
%        Higher 's' increases exploration; lower 's' increases exploitation.
%
% Outputs:
%   O1, O2 : (D x n) Offspring matrices

    % Set default scale parameter if not provided
    if nargin < 4 || isempty(s), s = 1.0; end
    
    % Get problem dimension (D) and number of pairs (n)
    [D, ~] = size(P);
    n = numel(I1);
    
    % Efficiently extract parent matrices using vectorized indexing
    p1 = P(:, I1);
    p2 = P(:, I2);
    
    % Pre-calculate the distance (scale of the search step)
    % This ensures the operator is self-adaptive to the population convergence.
    dist = abs(p1 - p2);
    
    % Generate two independent sets of Logistic random variables (beta)
    % Logistic PDF: f(x; 0, s) = exp(-x/s) / (s * (1 + exp(-x/s))^2)
    % Inverse CDF: x = s * ln(u / (1 - u))
    % Note: Using two independent betas (beta1, beta2) provides better 
    % diversity than a single symmetric beta.
    u1 = rand(D, n);
    u2 = rand(D, n);
    
    % Vectorized Inverse CDF transformation
    % Adding eps prevents log(0) or division by zero errors
    beta1 = s * log(u1 ./ (1 - u1 + eps));
    beta2 = s * log(u2 ./ (1 - u2 + eps));
    
    % Generate offspring: Perturb parents by the logistic-scaled distance
    % This maintains the spatial correlation of the parents while 
    % allowing for "heavy-tail" jumps to escape local optima.
    O1 = p1 + beta1 .* dist;
    O2 = p2 + beta2 .* dist;
    
end